/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#2a3a4f",
        "on-primary-fixed": "#001356",
        "on-tertiary": "#2f3131",
        "surface-container-lowest": "#000f21",
        "tertiary-fixed": "#e2e2e2",
        "error": "#ffb4ab",
        "tertiary-container": "#6c6d6d",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#474647",
        "outline": "#8e90a2",
        "on-secondary": "#313031",
        "primary-fixed-dim": "#b8c3ff",
        "surface-tint": "#b8c3ff",
        "on-secondary-container": "#bab8b9",
        "surface-container": "#102034",
        "secondary": "#c8c6c7",
        "surface-container-high": "#1b2b3f",
        "on-secondary-fixed": "#1c1b1c",
        "on-error": "#690005",
        "on-surface": "#d3e4fe",
        "outline-variant": "#434656",
        "primary-container": "#2e5bff",
        "tertiary": "#c6c6c7",
        "secondary-container": "#4a494a",
        "surface-dim": "#031427",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-container": "#efefff",
        "on-tertiary-container": "#f0f0f0",
        "inverse-primary": "#124af0",
        "primary-fixed": "#dde1ff",
        "surface-container-highest": "#26364a",
        "on-primary-fixed-variant": "#0035be",
        "surface-container-low": "#0b1c30",
        "on-surface-variant": "#c4c5d9",
        "background": "#031427",
        "on-background": "#d3e4fe",
        "surface": "#031427",
        "primary": "#b8c3ff",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#26364a",
        "secondary-fixed": "#e5e2e3",
        "inverse-surface": "#d3e4fe",
        "on-primary": "#002388",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#213145",
        "secondary-fixed-dim": "#c8c6c7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "title-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
